# -*- coding: utf-8 -*-
"""Numpy.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1p8UDSgI9QNO_Bl8-9PXdvocHjkEbVJK-
"""

import pandas as pd
import numpy as np

x = np.arange(10)
x

x[5]

x[:5] #first 5 elements

x[5:]

"""array slicing x[start:stop:step]"""

x[::2] #every second element starting from 0

x[1::2] #every second element starting from 1

x[::-1]

x[5::-2] #reversed every other element from index 5

"""Multidimentional array

"""

x2=np.random.randint(0,10,(3,3))
x2

x2 [:2,:3] #two rows, three columns

x2 [:3,::2] #all rows and every OTHER column